/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as DemoStoreRouteImport } from './routes/demo/store'
import { Route as DemoSentryRouteImport } from './routes/demo/sentry'
import { Route as DemoAiStructuredRouteImport } from './routes/demo/ai-structured'
import { Route as DemoAiImageRouteImport } from './routes/demo/ai-image'
import { Route as DemoAiChatRouteImport } from './routes/demo/ai-chat'
import { Route as ApiSentryExampleRouteImport } from './routes/api/sentry-example'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as DemoGuitarsIndexRouteImport } from './routes/demo/guitars/index'
import { Route as LangProductsIndexRouteImport } from './routes/$lang/products/index'
import { Route as DemoGuitarsGuitarIdRouteImport } from './routes/demo/guitars/$guitarId'
import { Route as LangProductsProductIdRouteImport } from './routes/$lang/products/$productId'
import { Route as DemoApiAiTtsRouteImport } from './routes/demo/api.ai.tts'
import { Route as DemoApiAiTranscriptionRouteImport } from './routes/demo/api.ai.transcription'
import { Route as DemoApiAiStructuredRouteImport } from './routes/demo/api.ai.structured'
import { Route as DemoApiAiImageRouteImport } from './routes/demo/api.ai.image'
import { Route as DemoApiAiChatRouteImport } from './routes/demo/api.ai.chat'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSentryRoute = DemoSentryRouteImport.update({
  id: '/sentry',
  path: '/sentry',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAiStructuredRoute = DemoAiStructuredRouteImport.update({
  id: '/ai-structured',
  path: '/ai-structured',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAiImageRoute = DemoAiImageRouteImport.update({
  id: '/ai-image',
  path: '/ai-image',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAiChatRoute = DemoAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => DemoRoute,
} as any)
const ApiSentryExampleRoute = ApiSentryExampleRouteImport.update({
  id: '/api/sentry-example',
  path: '/api/sentry-example',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LangRoute,
} as any)
const DemoGuitarsIndexRoute = DemoGuitarsIndexRouteImport.update({
  id: '/guitars/',
  path: '/guitars/',
  getParentRoute: () => DemoRoute,
} as any)
const LangProductsIndexRoute = LangProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => LangRoute,
} as any)
const DemoGuitarsGuitarIdRoute = DemoGuitarsGuitarIdRouteImport.update({
  id: '/guitars/$guitarId',
  path: '/guitars/$guitarId',
  getParentRoute: () => DemoRoute,
} as any)
const LangProductsProductIdRoute = LangProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => LangRoute,
} as any)
const DemoApiAiTtsRoute = DemoApiAiTtsRouteImport.update({
  id: '/api/ai/tts',
  path: '/api/ai/tts',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApiAiTranscriptionRoute = DemoApiAiTranscriptionRouteImport.update({
  id: '/api/ai/transcription',
  path: '/api/ai/transcription',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApiAiStructuredRoute = DemoApiAiStructuredRouteImport.update({
  id: '/api/ai/structured',
  path: '/api/ai/structured',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApiAiImageRoute = DemoApiAiImageRouteImport.update({
  id: '/api/ai/image',
  path: '/api/ai/image',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApiAiChatRoute = DemoApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/about': typeof AboutRoute
  '/demo': typeof DemoRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/sentry': typeof DemoSentryRoute
  '/demo/store': typeof DemoStoreRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/products/$productId': typeof LangProductsProductIdRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/$lang/products/': typeof LangProductsIndexRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/demo': typeof DemoRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/sentry': typeof DemoSentryRoute
  '/demo/store': typeof DemoStoreRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/products/$productId': typeof LangProductsProductIdRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/$lang/products': typeof LangProductsIndexRoute
  '/demo/guitars': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/about': typeof AboutRoute
  '/demo': typeof DemoRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/api/sentry-example': typeof ApiSentryExampleRoute
  '/demo/ai-chat': typeof DemoAiChatRoute
  '/demo/ai-image': typeof DemoAiImageRoute
  '/demo/ai-structured': typeof DemoAiStructuredRoute
  '/demo/sentry': typeof DemoSentryRoute
  '/demo/store': typeof DemoStoreRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/products/$productId': typeof LangProductsProductIdRoute
  '/demo/guitars/$guitarId': typeof DemoGuitarsGuitarIdRoute
  '/$lang/products/': typeof LangProductsIndexRoute
  '/demo/guitars/': typeof DemoGuitarsIndexRoute
  '/demo/api/ai/chat': typeof DemoApiAiChatRoute
  '/demo/api/ai/image': typeof DemoApiAiImageRoute
  '/demo/api/ai/structured': typeof DemoApiAiStructuredRoute
  '/demo/api/ai/transcription': typeof DemoApiAiTranscriptionRoute
  '/demo/api/ai/tts': typeof DemoApiAiTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/about'
    | '/demo'
    | '/$lang/about'
    | '/api/sentry-example'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/sentry'
    | '/demo/store'
    | '/sitemap/xml'
    | '/$lang/'
    | '/$lang/products/$productId'
    | '/demo/guitars/$guitarId'
    | '/$lang/products/'
    | '/demo/guitars/'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/demo'
    | '/$lang/about'
    | '/api/sentry-example'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/sentry'
    | '/demo/store'
    | '/sitemap/xml'
    | '/$lang'
    | '/$lang/products/$productId'
    | '/demo/guitars/$guitarId'
    | '/$lang/products'
    | '/demo/guitars'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/about'
    | '/demo'
    | '/$lang/about'
    | '/api/sentry-example'
    | '/demo/ai-chat'
    | '/demo/ai-image'
    | '/demo/ai-structured'
    | '/demo/sentry'
    | '/demo/store'
    | '/sitemap/xml'
    | '/$lang/'
    | '/$lang/products/$productId'
    | '/demo/guitars/$guitarId'
    | '/$lang/products/'
    | '/demo/guitars/'
    | '/demo/api/ai/chat'
    | '/demo/api/ai/image'
    | '/demo/api/ai/structured'
    | '/demo/api/ai/transcription'
    | '/demo/api/ai/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AboutRoute: typeof AboutRoute
  DemoRoute: typeof DemoRouteWithChildren
  ApiSentryExampleRoute: typeof ApiSentryExampleRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/sentry': {
      id: '/demo/sentry'
      path: '/sentry'
      fullPath: '/demo/sentry'
      preLoaderRoute: typeof DemoSentryRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ai-structured': {
      id: '/demo/ai-structured'
      path: '/ai-structured'
      fullPath: '/demo/ai-structured'
      preLoaderRoute: typeof DemoAiStructuredRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ai-image': {
      id: '/demo/ai-image'
      path: '/ai-image'
      fullPath: '/demo/ai-image'
      preLoaderRoute: typeof DemoAiImageRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ai-chat': {
      id: '/demo/ai-chat'
      path: '/ai-chat'
      fullPath: '/demo/ai-chat'
      preLoaderRoute: typeof DemoAiChatRouteImport
      parentRoute: typeof DemoRoute
    }
    '/api/sentry-example': {
      id: '/api/sentry-example'
      path: '/api/sentry-example'
      fullPath: '/api/sentry-example'
      preLoaderRoute: typeof ApiSentryExampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof LangRoute
    }
    '/demo/guitars/': {
      id: '/demo/guitars/'
      path: '/guitars'
      fullPath: '/demo/guitars/'
      preLoaderRoute: typeof DemoGuitarsIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/$lang/products/': {
      id: '/$lang/products/'
      path: '/products'
      fullPath: '/$lang/products/'
      preLoaderRoute: typeof LangProductsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/demo/guitars/$guitarId': {
      id: '/demo/guitars/$guitarId'
      path: '/guitars/$guitarId'
      fullPath: '/demo/guitars/$guitarId'
      preLoaderRoute: typeof DemoGuitarsGuitarIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/$lang/products/$productId': {
      id: '/$lang/products/$productId'
      path: '/products/$productId'
      fullPath: '/$lang/products/$productId'
      preLoaderRoute: typeof LangProductsProductIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/demo/api/ai/tts': {
      id: '/demo/api/ai/tts'
      path: '/api/ai/tts'
      fullPath: '/demo/api/ai/tts'
      preLoaderRoute: typeof DemoApiAiTtsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/api/ai/transcription': {
      id: '/demo/api/ai/transcription'
      path: '/api/ai/transcription'
      fullPath: '/demo/api/ai/transcription'
      preLoaderRoute: typeof DemoApiAiTranscriptionRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/api/ai/structured': {
      id: '/demo/api/ai/structured'
      path: '/api/ai/structured'
      fullPath: '/demo/api/ai/structured'
      preLoaderRoute: typeof DemoApiAiStructuredRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/api/ai/image': {
      id: '/demo/api/ai/image'
      path: '/api/ai/image'
      fullPath: '/demo/api/ai/image'
      preLoaderRoute: typeof DemoApiAiImageRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/api/ai/chat': {
      id: '/demo/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/demo/api/ai/chat'
      preLoaderRoute: typeof DemoApiAiChatRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface LangRouteChildren {
  LangAboutRoute: typeof LangAboutRoute
  LangIndexRoute: typeof LangIndexRoute
  LangProductsProductIdRoute: typeof LangProductsProductIdRoute
  LangProductsIndexRoute: typeof LangProductsIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAboutRoute: LangAboutRoute,
  LangIndexRoute: LangIndexRoute,
  LangProductsProductIdRoute: LangProductsProductIdRoute,
  LangProductsIndexRoute: LangProductsIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

interface DemoRouteChildren {
  DemoAiChatRoute: typeof DemoAiChatRoute
  DemoAiImageRoute: typeof DemoAiImageRoute
  DemoAiStructuredRoute: typeof DemoAiStructuredRoute
  DemoSentryRoute: typeof DemoSentryRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoGuitarsGuitarIdRoute: typeof DemoGuitarsGuitarIdRoute
  DemoGuitarsIndexRoute: typeof DemoGuitarsIndexRoute
  DemoApiAiChatRoute: typeof DemoApiAiChatRoute
  DemoApiAiImageRoute: typeof DemoApiAiImageRoute
  DemoApiAiStructuredRoute: typeof DemoApiAiStructuredRoute
  DemoApiAiTranscriptionRoute: typeof DemoApiAiTranscriptionRoute
  DemoApiAiTtsRoute: typeof DemoApiAiTtsRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAiChatRoute: DemoAiChatRoute,
  DemoAiImageRoute: DemoAiImageRoute,
  DemoAiStructuredRoute: DemoAiStructuredRoute,
  DemoSentryRoute: DemoSentryRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoGuitarsGuitarIdRoute: DemoGuitarsGuitarIdRoute,
  DemoGuitarsIndexRoute: DemoGuitarsIndexRoute,
  DemoApiAiChatRoute: DemoApiAiChatRoute,
  DemoApiAiImageRoute: DemoApiAiImageRoute,
  DemoApiAiStructuredRoute: DemoApiAiStructuredRoute,
  DemoApiAiTranscriptionRoute: DemoApiAiTranscriptionRoute,
  DemoApiAiTtsRoute: DemoApiAiTtsRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AboutRoute: AboutRoute,
  DemoRoute: DemoRouteWithChildren,
  ApiSentryExampleRoute: ApiSentryExampleRoute,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
